# Generated by Django 3.0.7 on 2020-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_type', models.CharField(choices=[('F', 'Free'), ('P', 'Plus')], default='F', max_length=1)),
                ('blog_title', models.TextField()),
                ('blog_description', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
